/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'missing' : IDL.Int,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'sport' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Text],
      [],
    ),
  'deleteMatch' : IDL.Func([IDL.Text], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinMatch' : IDL.Func([IDL.Text], [], []),
  'searchMatchesByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Match)], ['query']),
  'searchMatchesBySport' : IDL.Func([IDL.Text], [IDL.Vec(Match)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'missing' : IDL.Int,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'sport' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Text],
        [],
      ),
    'deleteMatch' : IDL.Func([IDL.Text], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinMatch' : IDL.Func([IDL.Text], [], []),
    'searchMatchesByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Match)],
        ['query'],
      ),
    'searchMatchesBySport' : IDL.Func([IDL.Text], [IDL.Vec(Match)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };